### ISSUE TITLE
Implement upgradable governance

### ISSUE THREAD

**Issue by jstolarek** [input-output-hk/partner-chains-smart-contracts#48]
We need to implement an upgradable governance mechanism as outlined in SIP-16.

## Requirements

Repeated from the SIP:

  * A default securing mechanism is a N-of-M multi sig where the partner chain developer is responsible for defining the values of N, M and the wallets in question
  * This should be configurable to allow arbitrary logic
     - The partner chain developer may have a DAO in place
     - They may be happy with a “proof of authority” solution with a manager NFT
  * This should be upgradeable (in case the partner chain developer eventually gets a governance mechanism to replace the default, or makes an upgrade to a previous mechanism)
  * Upgrading this mechanism should require the prover to show they can meet at least the current security threshold

## Remaining implementation outline

  * [ ] input-output-hk/partner-chains-smart-contracts#55
  * [ ] input-output-hk/partner-chains-smart-contracts#56
  * [ ] input-output-hk/partner-chains-smart-contracts#57
  * [ ] input-output-hk/partner-chains-smart-contracts#60

----

IOG Jira: https://input-output.atlassian.net/browse/ETCM-7669
